### ISSUE TITLE
Is this finished?

### ISSUE THREAD

**Issue by MIOGMIOG** [sulu5890/FreedomChat#2]
I did not found any download and compiling with github actions will crash.

**Comment by cobaltgit** [comment]
Hello. I have submitted a pull request to update this project to use 1.19.1, as well as compiling a JAR file for it. I will contact the developer of FreedomChat and see if they will release the new JAR

**Comment by Oharass** [comment]
the version up was designed for an old snapshot... I just update now and add release.
